### ISSUE TITLE
Cannot get localhost:8000/admin to work

### ISSUE THREAD

**Issue by bjoh-01** [DusanMadar/geodjango-tutorial-kickoff#1]
Thanks for creating this docker image. I'm having trouble getting to the django welcome or admin screen.

**Comment by DusanMadar** [comment]
@bjoh-01 I just tried following the readme instructions and it works.

Can you describe what didn't work for you, please?

**Comment by DusanMadar** [comment]
Right, so I've realized that the readme available on GH was not complete. :facepalm: It's updated now and explains how to start Django. 

Feel free to close the issue if that helps.

**Comment by bjoh-01** [comment]
That definitely helped. Thanks again!
